"""This module defines some constants"""

BROADCAST_ADDRESS = 255
DEFAULT_CLEAR_TIME = 450
DEFAULT_SET_TIME = 1200
FRAMEBUFFER_FRAME_SIZE = 232
RENDERING_OPTIONS_FRAME_SIZE = 464
POWER_FRAME_SIZE = 2
RENDER_FRAME_SIZE = 2
LATENCY = 1
EMPTY_FRAME = [[False for y in range(0, 16)] for x in range(0, 115)]
COLORS = 14
BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE, GRAY, BUTTON, HLITE, ERR, WARN, NOTE = range(
    COLORS)
